sudo: false
language: go
go:
  - 1.8.x
install:
  - nvm install node
  - npm install -g source-map-support
  - go get -u github.com/gopherjs/gopherjs
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get -u github.com/haya14busa/goverage
  - gometalinter.v1 --config=.gometalinter.json --install
before_script:
  - export NODE_PATH="/usr/local/lib/node_modules"
script:
  # Fetch dependencies.
  - go get -t -v ./...

  # Consult gometalinter, megacheck tools.
  - gometalinter.v1 --config=.gometalinter.json --severity=golint:error . ./example/...
  - gometalinter.v1 --config=.gometalinter.json ./elem/... event/... prop/... storeutil/... # TODO(slimsag): address these linter errors
  - megacheck ./...
  - megacheck -tags=js ./...

  # Test with Go compiler and GopherJS compiler.
  - go test -v -race ./...
  - gopherjs test -v $(go list ./...)

  # Generate and upload coverage to codecov.io
  - goverage -covermode=atomic -coverprofile=coverage.out $(go list ./... | grep -v -e vecty/elem -e vecty/event -e vecty/example -e vecty/prop -e vecty/style)
  - include_cov=coverage.out bash <(curl -s https://codecov.io/bash)
